menu:
  Home: /
  Archives: /archives

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# valine comment
valine: true
leancloud_id: HW01rEmb5YbfM7jD6PUf3PUv-gzGzoHsz
leancloud_key: hV2h0dbqaFKgxOWo4GiCKd80

# disqus comment
disqus: false
disqus_shortname:

# google analytics
googleTrackId:
